version: '3'
services:
  frontend:
    build: ./canitrun
    ports:
      - '3000:3000'
  backend:
    build: ./server
    ports:
      - '3001:3001'
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

