version: '3'
services:
  frontend:
    build: ./canitrun
    ports:
      - '3000:3000'
  backend:
    build: ./server
    ports:
      - '3001:3001'
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
