version: "3"

services:
  mysql:   
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_allowed_packet=128M
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=MAIN_DB
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
  app:
    build: ./
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - app_data:/path/in/container

volumes:
  mysql_data:
  app_data:
    driver: efs