version: '3.8'
services:
  #### Database
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    hostname: postgres
    networks:
      - appius-net
networks:
  appius-net:
